#define heltal int
#define flyttal float
#define dubbel double
#define lång long
#define boolesk bool
#define inget void
#define sträng std::string
#define sträng_vy std::string_view
#define konstant const
#define huvud main
#define nolla 0.0
#define samla std::accumulate
#define till_liten_bokstav std::tolower
#define är_ett_mellanslag isspace
#define är_ett_tal isdigit
#define är_en_stor_bokstav isupper
#define bokstav char
#define börja begin
#define sluta end
#define retunera return
#define om if
#define inte !
#define terminal_text_ut std::cout
#define avslutning_av_textrad std::endl
#define lägg_till +=
#define referens &
#define minnesadress *
#define karta std::map
#define osorterad_karta std::unordered_map
#define börja_block {
#define sluta_block }
#define klass class
#define struktur struct
#define enumerationsklass enum class
#define uppräkning enum
#define upprepning for
#define medan while
#define gör do
#define annars else
#define annars_om else if
#define bryt break
#define fortsätt continue
#define storlek sizeof
#define ny new
#define ta_bort delete
#define växel switch
#define fall case
#define standardfall default
#define försök try
#define fånga catch
#define kasta throw
#define dynamisk_typomvandling dynamic_cast
#define statisk_typomvandling static_cast
#define konstant_typomvandling const_cast
#define omtolka_typomvandling reinterpret_cast
#define positiv unsigned
#define möjligtvis_negativ signed
#define skyddad protected
#define vänn friend
#define offentlig public
#define privat private
#define automatisk auto
#define statisk static
#define ingen_minnesaddress nullptr
#define hemlös nullptr
#define konstantuttryck constexpr
#define instabil volatile
#define virituell virtual
#define skriv_över override
#define slutgiltig final
#define slutgiltig_vänskap slutgiltig vänn
#define heltal_med_8_bitar int8_t
#define heltal_med_16bitar int16_t
#define heltal_med_32_bitar int32_t
#define heltal_med_64_bitar int64_t
#define positivt_heltal_med_8_bitar uint8_t
#define positivt_heltal_med_16_bitar uint16_t
#define positivt_heltal_med_32_bitar uint32_t
#define positivt_heltal_med_64_bitar uint64_t
#define detta this
#define typdefiniera typedef
#define använder using
#define namnutrymme namespace
#define exklusiv_eller ^
#define ändringsbar mutable
#define multiplicera *
#define dividera /
#define modulo %
#define plus +
#define minus -
#define mindre_än <
#define mindre_eller_likamed <=
#define större_än >
#define större_eller_likamed >=
#define lika_med ==
#define inte_likamed !=
#define och &&
#define eller ||
#define avsluta_uttryck ;
#define skifta_bitar_höger >>
#define skifta_bitar_vänster <<
#define medlemspil ->
#define börja_kommentar /*
#define avsluta_kommentar */
#define sant true
#define falskt false
#define unik_pekare std::unique_ptr
#define delad_pekare std::shared_ptr
#define skapa_unik std::make_unique
#define skapa_delad std::make_shared
#define tilldela =
#define förstörare ~